닉네임: bohchoi

문제 플랫폼: 프로그래머스

문제 이름 또는 번호: n 번째 원소부터

문제 링크:https://school.programmers.co.kr/learn/courses/30/lessons/181892

오늘의 메모(선택): 
    answer 벡터는 비어 있는 상태인데, answer.at(i)로 존재하지 않는 인덱스에 접근하고 있어서 std::out_of_range 오류가 발생했다. 이는 런타임 오류이며, 코어 덤프를 유발할 수 있다.
    이를 해결하기 위해 벡터 answer에 **answer.push_back()**으로 값을 넣었다.

코드(선택):

```cpp
#include <string>
#include <vector>

using namespace std;

vector<int> solution(vector<int> num_list, int n) {
    vector<int> answer;
    int len = num_list.size();
    
    for (int i = n - 1; i < len; i++)
        answer.push_back(num_list.at(i));
    return answer;
}

```